# apiVersion: v1
# kind: Service
# metadata:
#   name: todolist-ui
# spec:
#   ports:
#   - port: 8080
#     targetPort: 8080
#   selector:
#     app: todolist-ui

# apiVersion: v1
# kind: Service
# metadata:
#   name: todolist-ui
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 8080
#       targetPort: 8080
#   selector:
#     app: todolist-ui
apiVersion: v1
kind: Service
metadata:
  name: todolist-ui
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: todolist-ui

